spring:
  elasticsearch:
    uris: http://8.137.112.190:9200
    username: elastic
    password: a7LGnm+H7tRIj+pqvK6j
    connection-timeout: 5s
    socket-timeout: 10s
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://8.137.112/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql
      mode: never
      #mode: always
  batch:
    job:
      enabled: false   #false表示不跟随SpringBoot启动