spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.137.112.190:3306/juxian?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: buercorp@20240104

  messages:
    basename: classpath:i18n/message
    fallback-to-system-locale: true
#  elasticsearch:
#    uris: https://8.137.112.190:9200
#    connection-timeout: 5s
#    socket-timeout: 10s
#    username: elastic
#    password: vTvyLWzr_QEmMZ6JPKKN


mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

logging:
  config: classpath:log/log4j2-dev.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html